# name of the pipeline
name: cd

on:
  # it will get executed on push
  push:
  # changes will be published to the main branch
    branches:
      - "main"
    paths:
    ## paths - changes in which files will trigger this file
      - "src/terraform/**"
      - ".github/workflow/**"

# setting up environment variables for reuse
env:
  # directory in which the terraform commands will be executed
  WORKING_DIRECTORY: "src/terraform"
  APPLICATION_NAME: "aztf"
  ENVIRONMENT_NAME: "dev"

jobs:
  terraform:
    # job will run on ubuntu based VM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 ## checks our the code from the repository - !important
      # its the process of fetching the code from my repository to the
      # environment where the workflow is running

      # set up terraform on ubuntu VM
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.5
          terraform_wrapper: false

      # Apply terraform configuration
      - name: Terraform Apply
        env:
          # ARM - Azure credentials for authentication and authorization, so we can interact with Azure resources
          ARM_SUBSCRIPTION_ID: ${{vars.ARM_SUBSCRIPTION_ID}}
          ARM_TENANT_ID: ${{vars.ARM_TENANT_ID}}
          ARM_CLIENT_ID: ${{vars.ARM_CLIENT_ID}}
          ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
          # Configure Terraform backend, to store the .state file
          BACKEND_RESOURCE_GROUP_NAME: ${{vars.BACKEND_RESOURCE_GROUP_NAME}}
          BACKEND_STORAGE_ACCOUNT_NAME: ${{vars.BACKEND_STORAGE_ACCOUNT_NAME}}
          BACKEND_STORAGE_CONTAINER_NAME: ${{vars.BACKEND_STORAGE_CONTAINER_NAME}}
          # Variables to pass values to Terraform configuration files
          TF_VAR_application_name: ${{env.APPLICATION_NAME}}
          TF_VAR_environment_name: ${{env.ENVIRONMENT_NAME}}
          # Key for storing the state file in the backend
          # this is how the file will be named inside the blob storage => aztf-dev
          # the name of the blob storage(container) will be tfstate by default
          TF_BACKEND_KEY: ${{env.APPLICATION_NAME}}-${{env.ENVIRONMENT_NAME}}
        # specifies directory in which will the commands beneath get executed
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          terraform init \
            -backend-config="resource_group_name=$BACKEND_RESOURCE_GROUP_NAME" \
            -backend-config="storage_account_name=$BACKEND_STORAGE_ACCOUNT_NAME" \
            -backend-config="container_name=$BACKEND_STORAGE_CONTAINER_NAME" \
            -backend-config="key=$TF_BACKEND_KEY"

          terraform apply -auto-approve
