name: ci

on:
  pull_request:
    branches: 
      - main
    paths:
    - "src/dotnet/GitHubDemo"

env:
  # this version has to be installed on the machine, on which we run this code
  DOTNET_VERSION: "6.0.401"
  WORKING_DIRECTORY: ./src/dotnet/GitHubDemo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Sets up .NET with specific version
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3 
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Install dependencies
        run: dotnet restore
        working-directory: ${{env.WORKING_DIRECTORY}}

      - name: Build
        #--no-restore = skips the implicit restore operation performed before
        run: dotnet build --configuration Release --no-restore
        working-directory: ${{env.WORKING_DIRECTORY}}

      - name: Test
        # --filter Category=Unit
        # only tests with specified category of Unit will be excecuted
        # we will set the Category=Unit int the C# code
        run: dotnet test --no-restore --verbosity normal --filter Category=Unit
        working-directory: ./src/dotnet/GitHubDemo.UnitTests
